// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fidentapi.proto

/*
Package fidentapi is a generated protocol buffer package.

It is generated from these files:
	fidentapi.proto

It has these top-level messages:
	ServiceRegistrationResponse
	ServiceRegistrationRequest
	AuthResponse
	AuthChallengeResponse
	AuthChallengeRequest
	PerformAuthRequest
	AuthKeyRequest
	AuthKeyResponse
	LoginTimestampResponse
	LoginTimestampRequest
	IdentityIDsResponse
	IdentityIDsRequest
	AccountAttribute
	AccountDetail
	AccountDetailResponse
	AccountDetailRequest
	GetManagementPermissionsRequest
	ManagementPermissionResponse
	ManagementPermissionsResponse
	AddManagementPermissionReponse
	AddManagementPermissionRequest
	RemoveManagementPermissionReponse
	RemoveManagementPermissionRequest
	Cookie
	CreateUserAccountRequest
	CreateUserAccountResponse
*/
package fidentapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceRegistrationResponse struct {
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	ServiceKey string `protobuf:"bytes,2,opt,name=service_key,json=serviceKey" json:"service_key,omitempty"`
}

func (m *ServiceRegistrationResponse) Reset()                    { *m = ServiceRegistrationResponse{} }
func (m *ServiceRegistrationResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceRegistrationResponse) ProtoMessage()               {}
func (*ServiceRegistrationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceRegistrationResponse) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *ServiceRegistrationResponse) GetServiceKey() string {
	if m != nil {
		return m.ServiceKey
	}
	return ""
}

type ServiceRegistrationRequest struct {
	ServiceName   string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	ServiceVendor string `protobuf:"bytes,2,opt,name=service_vendor,json=serviceVendor" json:"service_vendor,omitempty"`
	SupportEmail  string `protobuf:"bytes,3,opt,name=support_email,json=supportEmail" json:"support_email,omitempty"`
}

func (m *ServiceRegistrationRequest) Reset()                    { *m = ServiceRegistrationRequest{} }
func (m *ServiceRegistrationRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceRegistrationRequest) ProtoMessage()               {}
func (*ServiceRegistrationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceRegistrationRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceRegistrationRequest) GetServiceVendor() string {
	if m != nil {
		return m.ServiceVendor
	}
	return ""
}

func (m *ServiceRegistrationRequest) GetSupportEmail() string {
	if m != nil {
		return m.SupportEmail
	}
	return ""
}

type AuthResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthChallengeResponse struct {
	Challenge string `protobuf:"bytes,1,opt,name=challenge" json:"challenge,omitempty"`
}

func (m *AuthChallengeResponse) Reset()                    { *m = AuthChallengeResponse{} }
func (m *AuthChallengeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthChallengeResponse) ProtoMessage()               {}
func (*AuthChallengeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthChallengeResponse) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type AuthChallengeRequest struct {
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	ProjectId  string `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *AuthChallengeRequest) Reset()                    { *m = AuthChallengeRequest{} }
func (m *AuthChallengeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthChallengeRequest) ProtoMessage()               {}
func (*AuthChallengeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthChallengeRequest) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *AuthChallengeRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type PerformAuthRequest struct {
	IdentityId        string `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	KeyHandle         string `protobuf:"bytes,2,opt,name=key_handle,json=keyHandle" json:"key_handle,omitempty"`
	ProjectId         string `protobuf:"bytes,3,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	ChallengeResponse string `protobuf:"bytes,4,opt,name=challenge_response,json=challengeResponse" json:"challenge_response,omitempty"`
}

func (m *PerformAuthRequest) Reset()                    { *m = PerformAuthRequest{} }
func (m *PerformAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*PerformAuthRequest) ProtoMessage()               {}
func (*PerformAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PerformAuthRequest) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *PerformAuthRequest) GetKeyHandle() string {
	if m != nil {
		return m.KeyHandle
	}
	return ""
}

func (m *PerformAuthRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *PerformAuthRequest) GetChallengeResponse() string {
	if m != nil {
		return m.ChallengeResponse
	}
	return ""
}

type AuthKeyRequest struct {
	Username         string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password         string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	UsageDescription string `protobuf:"bytes,3,opt,name=usage_description,json=usageDescription" json:"usage_description,omitempty"`
}

func (m *AuthKeyRequest) Reset()                    { *m = AuthKeyRequest{} }
func (m *AuthKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthKeyRequest) ProtoMessage()               {}
func (*AuthKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AuthKeyRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthKeyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthKeyRequest) GetUsageDescription() string {
	if m != nil {
		return m.UsageDescription
	}
	return ""
}

type AuthKeyResponse struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	KeyHandle  string `protobuf:"bytes,4,opt,name=key_handle,json=keyHandle" json:"key_handle,omitempty"`
}

func (m *AuthKeyResponse) Reset()                    { *m = AuthKeyResponse{} }
func (m *AuthKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthKeyResponse) ProtoMessage()               {}
func (*AuthKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AuthKeyResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthKeyResponse) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *AuthKeyResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *AuthKeyResponse) GetKeyHandle() string {
	if m != nil {
		return m.KeyHandle
	}
	return ""
}

type LoginTimestampResponse struct {
	Results map[string]int64 `protobuf:"bytes,1,rep,name=results" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *LoginTimestampResponse) Reset()                    { *m = LoginTimestampResponse{} }
func (m *LoginTimestampResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginTimestampResponse) ProtoMessage()               {}
func (*LoginTimestampResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LoginTimestampResponse) GetResults() map[string]int64 {
	if m != nil {
		return m.Results
	}
	return nil
}

type LoginTimestampRequest struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
}

func (m *LoginTimestampRequest) Reset()                    { *m = LoginTimestampRequest{} }
func (m *LoginTimestampRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginTimestampRequest) ProtoMessage()               {}
func (*LoginTimestampRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LoginTimestampRequest) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

type IdentityIDsResponse struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
}

func (m *IdentityIDsResponse) Reset()                    { *m = IdentityIDsResponse{} }
func (m *IdentityIDsResponse) String() string            { return proto.CompactTextString(m) }
func (*IdentityIDsResponse) ProtoMessage()               {}
func (*IdentityIDsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IdentityIDsResponse) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

type IdentityIDsRequest struct {
}

func (m *IdentityIDsRequest) Reset()                    { *m = IdentityIDsRequest{} }
func (m *IdentityIDsRequest) String() string            { return proto.CompactTextString(m) }
func (*IdentityIDsRequest) ProtoMessage()               {}
func (*IdentityIDsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type AccountAttribute struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *AccountAttribute) Reset()                    { *m = AccountAttribute{} }
func (m *AccountAttribute) String() string            { return proto.CompactTextString(m) }
func (*AccountAttribute) ProtoMessage()               {}
func (*AccountAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AccountAttribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AccountAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AccountDetail struct {
	IdentityId string              `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	Username   string              `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Attributes []*AccountAttribute `protobuf:"bytes,3,rep,name=attributes" json:"attributes,omitempty"`
	Created    int64               `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
}

func (m *AccountDetail) Reset()                    { *m = AccountDetail{} }
func (m *AccountDetail) String() string            { return proto.CompactTextString(m) }
func (*AccountDetail) ProtoMessage()               {}
func (*AccountDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AccountDetail) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *AccountDetail) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountDetail) GetAttributes() []*AccountAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *AccountDetail) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type AccountDetailResponse struct {
	Results []*AccountDetail `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *AccountDetailResponse) Reset()                    { *m = AccountDetailResponse{} }
func (m *AccountDetailResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountDetailResponse) ProtoMessage()               {}
func (*AccountDetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AccountDetailResponse) GetResults() []*AccountDetail {
	if m != nil {
		return m.Results
	}
	return nil
}

type AccountDetailRequest struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
}

func (m *AccountDetailRequest) Reset()                    { *m = AccountDetailRequest{} }
func (m *AccountDetailRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountDetailRequest) ProtoMessage()               {}
func (*AccountDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AccountDetailRequest) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

type GetManagementPermissionsRequest struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
}

func (m *GetManagementPermissionsRequest) Reset()         { *m = GetManagementPermissionsRequest{} }
func (m *GetManagementPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetManagementPermissionsRequest) ProtoMessage()    {}
func (*GetManagementPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16}
}

func (m *GetManagementPermissionsRequest) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

type ManagementPermissionResponse struct {
	IdentityId  string   `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *ManagementPermissionResponse) Reset()                    { *m = ManagementPermissionResponse{} }
func (m *ManagementPermissionResponse) String() string            { return proto.CompactTextString(m) }
func (*ManagementPermissionResponse) ProtoMessage()               {}
func (*ManagementPermissionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ManagementPermissionResponse) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *ManagementPermissionResponse) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ManagementPermissionsResponse struct {
	Results []*ManagementPermissionResponse `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ManagementPermissionsResponse) Reset()                    { *m = ManagementPermissionsResponse{} }
func (m *ManagementPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ManagementPermissionsResponse) ProtoMessage()               {}
func (*ManagementPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ManagementPermissionsResponse) GetResults() []*ManagementPermissionResponse {
	if m != nil {
		return m.Results
	}
	return nil
}

type AddManagementPermissionReponse struct {
}

func (m *AddManagementPermissionReponse) Reset()                    { *m = AddManagementPermissionReponse{} }
func (m *AddManagementPermissionReponse) String() string            { return proto.CompactTextString(m) }
func (*AddManagementPermissionReponse) ProtoMessage()               {}
func (*AddManagementPermissionReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type AddManagementPermissionRequest struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	Permission string   `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`
}

func (m *AddManagementPermissionRequest) Reset()                    { *m = AddManagementPermissionRequest{} }
func (m *AddManagementPermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*AddManagementPermissionRequest) ProtoMessage()               {}
func (*AddManagementPermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *AddManagementPermissionRequest) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

func (m *AddManagementPermissionRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type RemoveManagementPermissionReponse struct {
}

func (m *RemoveManagementPermissionReponse) Reset()         { *m = RemoveManagementPermissionReponse{} }
func (m *RemoveManagementPermissionReponse) String() string { return proto.CompactTextString(m) }
func (*RemoveManagementPermissionReponse) ProtoMessage()    {}
func (*RemoveManagementPermissionReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21}
}

type RemoveManagementPermissionRequest struct {
	IdentityId []string `protobuf:"bytes,1,rep,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	Permission string   `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`
}

func (m *RemoveManagementPermissionRequest) Reset()         { *m = RemoveManagementPermissionRequest{} }
func (m *RemoveManagementPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveManagementPermissionRequest) ProtoMessage()    {}
func (*RemoveManagementPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *RemoveManagementPermissionRequest) GetIdentityId() []string {
	if m != nil {
		return m.IdentityId
	}
	return nil
}

func (m *RemoveManagementPermissionRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type Cookie struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value        string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Domain       string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	ExpiresEpoch int64  `protobuf:"varint,4,opt,name=expires_epoch,json=expiresEpoch" json:"expires_epoch,omitempty"`
	Secure       bool   `protobuf:"varint,5,opt,name=secure" json:"secure,omitempty"`
	HttpOnly     bool   `protobuf:"varint,6,opt,name=http_only,json=httpOnly" json:"http_only,omitempty"`
}

func (m *Cookie) Reset()                    { *m = Cookie{} }
func (m *Cookie) String() string            { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()               {}
func (*Cookie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *Cookie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cookie) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Cookie) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Cookie) GetExpiresEpoch() int64 {
	if m != nil {
		return m.ExpiresEpoch
	}
	return 0
}

func (m *Cookie) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *Cookie) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

type CreateUserAccountRequest struct {
	EmailAddress        string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress" json:"email_address,omitempty"`
	IssueTemporaryToken bool   `protobuf:"varint,2,opt,name=issue_temporary_token,json=issueTemporaryToken" json:"issue_temporary_token,omitempty"`
}

func (m *CreateUserAccountRequest) Reset()                    { *m = CreateUserAccountRequest{} }
func (m *CreateUserAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserAccountRequest) ProtoMessage()               {}
func (*CreateUserAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateUserAccountRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateUserAccountRequest) GetIssueTemporaryToken() bool {
	if m != nil {
		return m.IssueTemporaryToken
	}
	return false
}

type CreateUserAccountResponse struct {
	IdentityId     string  `protobuf:"bytes,1,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	TemporaryToken *Cookie `protobuf:"bytes,2,opt,name=temporary_token,json=temporaryToken" json:"temporary_token,omitempty"`
}

func (m *CreateUserAccountResponse) Reset()                    { *m = CreateUserAccountResponse{} }
func (m *CreateUserAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserAccountResponse) ProtoMessage()               {}
func (*CreateUserAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CreateUserAccountResponse) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *CreateUserAccountResponse) GetTemporaryToken() *Cookie {
	if m != nil {
		return m.TemporaryToken
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceRegistrationResponse)(nil), "fidentapi.ServiceRegistrationResponse")
	proto.RegisterType((*ServiceRegistrationRequest)(nil), "fidentapi.ServiceRegistrationRequest")
	proto.RegisterType((*AuthResponse)(nil), "fidentapi.AuthResponse")
	proto.RegisterType((*AuthChallengeResponse)(nil), "fidentapi.AuthChallengeResponse")
	proto.RegisterType((*AuthChallengeRequest)(nil), "fidentapi.AuthChallengeRequest")
	proto.RegisterType((*PerformAuthRequest)(nil), "fidentapi.PerformAuthRequest")
	proto.RegisterType((*AuthKeyRequest)(nil), "fidentapi.AuthKeyRequest")
	proto.RegisterType((*AuthKeyResponse)(nil), "fidentapi.AuthKeyResponse")
	proto.RegisterType((*LoginTimestampResponse)(nil), "fidentapi.LoginTimestampResponse")
	proto.RegisterType((*LoginTimestampRequest)(nil), "fidentapi.LoginTimestampRequest")
	proto.RegisterType((*IdentityIDsResponse)(nil), "fidentapi.IdentityIDsResponse")
	proto.RegisterType((*IdentityIDsRequest)(nil), "fidentapi.IdentityIDsRequest")
	proto.RegisterType((*AccountAttribute)(nil), "fidentapi.AccountAttribute")
	proto.RegisterType((*AccountDetail)(nil), "fidentapi.AccountDetail")
	proto.RegisterType((*AccountDetailResponse)(nil), "fidentapi.AccountDetailResponse")
	proto.RegisterType((*AccountDetailRequest)(nil), "fidentapi.AccountDetailRequest")
	proto.RegisterType((*GetManagementPermissionsRequest)(nil), "fidentapi.GetManagementPermissionsRequest")
	proto.RegisterType((*ManagementPermissionResponse)(nil), "fidentapi.ManagementPermissionResponse")
	proto.RegisterType((*ManagementPermissionsResponse)(nil), "fidentapi.ManagementPermissionsResponse")
	proto.RegisterType((*AddManagementPermissionReponse)(nil), "fidentapi.AddManagementPermissionReponse")
	proto.RegisterType((*AddManagementPermissionRequest)(nil), "fidentapi.AddManagementPermissionRequest")
	proto.RegisterType((*RemoveManagementPermissionReponse)(nil), "fidentapi.RemoveManagementPermissionReponse")
	proto.RegisterType((*RemoveManagementPermissionRequest)(nil), "fidentapi.RemoveManagementPermissionRequest")
	proto.RegisterType((*Cookie)(nil), "fidentapi.Cookie")
	proto.RegisterType((*CreateUserAccountRequest)(nil), "fidentapi.CreateUserAccountRequest")
	proto.RegisterType((*CreateUserAccountResponse)(nil), "fidentapi.CreateUserAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	// Pre-authentication methods
	GetAuthenticationChallenge(ctx context.Context, in *AuthChallengeRequest, opts ...grpc.CallOption) (*AuthChallengeResponse, error)
	PerformAuthentication(ctx context.Context, in *PerformAuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Account generation / management
	GetNewAuthenticationKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AuthKeyResponse, error)
	CreateServiceAccount(ctx context.Context, in *ServiceRegistrationRequest, opts ...grpc.CallOption) (*ServiceRegistrationResponse, error)
	CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error)
	// Identity queries
	GetLastLoginTimestamps(ctx context.Context, in *LoginTimestampRequest, opts ...grpc.CallOption) (*LoginTimestampResponse, error)
	GetAccountDetails(ctx context.Context, in *AccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailResponse, error)
	GetAllIdentityIDs(ctx context.Context, in *IdentityIDsRequest, opts ...grpc.CallOption) (*IdentityIDsResponse, error)
	// Management API permission management
	GetManagementPermissionsForIdentityIDs(ctx context.Context, in *GetManagementPermissionsRequest, opts ...grpc.CallOption) (*ManagementPermissionsResponse, error)
	AddManagementPermissionToIdentityIDs(ctx context.Context, in *AddManagementPermissionRequest, opts ...grpc.CallOption) (*AddManagementPermissionReponse, error)
	RemoveManagementPermissionFromIdentityIDs(ctx context.Context, in *RemoveManagementPermissionRequest, opts ...grpc.CallOption) (*RemoveManagementPermissionReponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetAuthenticationChallenge(ctx context.Context, in *AuthChallengeRequest, opts ...grpc.CallOption) (*AuthChallengeResponse, error) {
	out := new(AuthChallengeResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetAuthenticationChallenge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) PerformAuthentication(ctx context.Context, in *PerformAuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/PerformAuthentication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetNewAuthenticationKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AuthKeyResponse, error) {
	out := new(AuthKeyResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetNewAuthenticationKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateServiceAccount(ctx context.Context, in *ServiceRegistrationRequest, opts ...grpc.CallOption) (*ServiceRegistrationResponse, error) {
	out := new(ServiceRegistrationResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/CreateServiceAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error) {
	out := new(CreateUserAccountResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/CreateUserAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetLastLoginTimestamps(ctx context.Context, in *LoginTimestampRequest, opts ...grpc.CallOption) (*LoginTimestampResponse, error) {
	out := new(LoginTimestampResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetLastLoginTimestamps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAccountDetails(ctx context.Context, in *AccountDetailRequest, opts ...grpc.CallOption) (*AccountDetailResponse, error) {
	out := new(AccountDetailResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetAccountDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAllIdentityIDs(ctx context.Context, in *IdentityIDsRequest, opts ...grpc.CallOption) (*IdentityIDsResponse, error) {
	out := new(IdentityIDsResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetAllIdentityIDs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetManagementPermissionsForIdentityIDs(ctx context.Context, in *GetManagementPermissionsRequest, opts ...grpc.CallOption) (*ManagementPermissionsResponse, error) {
	out := new(ManagementPermissionsResponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/GetManagementPermissionsForIdentityIDs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AddManagementPermissionToIdentityIDs(ctx context.Context, in *AddManagementPermissionRequest, opts ...grpc.CallOption) (*AddManagementPermissionReponse, error) {
	out := new(AddManagementPermissionReponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/AddManagementPermissionToIdentityIDs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RemoveManagementPermissionFromIdentityIDs(ctx context.Context, in *RemoveManagementPermissionRequest, opts ...grpc.CallOption) (*RemoveManagementPermissionReponse, error) {
	out := new(RemoveManagementPermissionReponse)
	err := grpc.Invoke(ctx, "/fidentapi.Auth/RemoveManagementPermissionFromIdentityIDs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	// Pre-authentication methods
	GetAuthenticationChallenge(context.Context, *AuthChallengeRequest) (*AuthChallengeResponse, error)
	PerformAuthentication(context.Context, *PerformAuthRequest) (*AuthResponse, error)
	// Account generation / management
	GetNewAuthenticationKey(context.Context, *AuthKeyRequest) (*AuthKeyResponse, error)
	CreateServiceAccount(context.Context, *ServiceRegistrationRequest) (*ServiceRegistrationResponse, error)
	CreateUserAccount(context.Context, *CreateUserAccountRequest) (*CreateUserAccountResponse, error)
	// Identity queries
	GetLastLoginTimestamps(context.Context, *LoginTimestampRequest) (*LoginTimestampResponse, error)
	GetAccountDetails(context.Context, *AccountDetailRequest) (*AccountDetailResponse, error)
	GetAllIdentityIDs(context.Context, *IdentityIDsRequest) (*IdentityIDsResponse, error)
	// Management API permission management
	GetManagementPermissionsForIdentityIDs(context.Context, *GetManagementPermissionsRequest) (*ManagementPermissionsResponse, error)
	AddManagementPermissionToIdentityIDs(context.Context, *AddManagementPermissionRequest) (*AddManagementPermissionReponse, error)
	RemoveManagementPermissionFromIdentityIDs(context.Context, *RemoveManagementPermissionRequest) (*RemoveManagementPermissionReponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GetAuthenticationChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetAuthenticationChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetAuthenticationChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetAuthenticationChallenge(ctx, req.(*AuthChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_PerformAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).PerformAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/PerformAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).PerformAuthentication(ctx, req.(*PerformAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetNewAuthenticationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetNewAuthenticationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetNewAuthenticationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetNewAuthenticationKey(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CreateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/CreateServiceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateServiceAccount(ctx, req.(*ServiceRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateUserAccount(ctx, req.(*CreateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetLastLoginTimestamps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetLastLoginTimestamps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetLastLoginTimestamps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetLastLoginTimestamps(ctx, req.(*LoginTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetAccountDetails(ctx, req.(*AccountDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetAllIdentityIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetAllIdentityIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetAllIdentityIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetAllIdentityIDs(ctx, req.(*IdentityIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetManagementPermissionsForIdentityIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagementPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetManagementPermissionsForIdentityIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/GetManagementPermissionsForIdentityIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetManagementPermissionsForIdentityIDs(ctx, req.(*GetManagementPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AddManagementPermissionToIdentityIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddManagementPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AddManagementPermissionToIdentityIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/AddManagementPermissionToIdentityIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AddManagementPermissionToIdentityIDs(ctx, req.(*AddManagementPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RemoveManagementPermissionFromIdentityIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveManagementPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RemoveManagementPermissionFromIdentityIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidentapi.Auth/RemoveManagementPermissionFromIdentityIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RemoveManagementPermissionFromIdentityIDs(ctx, req.(*RemoveManagementPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fidentapi.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthenticationChallenge",
			Handler:    _Auth_GetAuthenticationChallenge_Handler,
		},
		{
			MethodName: "PerformAuthentication",
			Handler:    _Auth_PerformAuthentication_Handler,
		},
		{
			MethodName: "GetNewAuthenticationKey",
			Handler:    _Auth_GetNewAuthenticationKey_Handler,
		},
		{
			MethodName: "CreateServiceAccount",
			Handler:    _Auth_CreateServiceAccount_Handler,
		},
		{
			MethodName: "CreateUserAccount",
			Handler:    _Auth_CreateUserAccount_Handler,
		},
		{
			MethodName: "GetLastLoginTimestamps",
			Handler:    _Auth_GetLastLoginTimestamps_Handler,
		},
		{
			MethodName: "GetAccountDetails",
			Handler:    _Auth_GetAccountDetails_Handler,
		},
		{
			MethodName: "GetAllIdentityIDs",
			Handler:    _Auth_GetAllIdentityIDs_Handler,
		},
		{
			MethodName: "GetManagementPermissionsForIdentityIDs",
			Handler:    _Auth_GetManagementPermissionsForIdentityIDs_Handler,
		},
		{
			MethodName: "AddManagementPermissionToIdentityIDs",
			Handler:    _Auth_AddManagementPermissionToIdentityIDs_Handler,
		},
		{
			MethodName: "RemoveManagementPermissionFromIdentityIDs",
			Handler:    _Auth_RemoveManagementPermissionFromIdentityIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fidentapi.proto",
}

func init() { proto.RegisterFile("fidentapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x53, 0xdb, 0x46,
	0x14, 0x8f, 0x6c, 0x42, 0xf0, 0xc3, 0x09, 0xb0, 0x01, 0xa2, 0x88, 0x00, 0x46, 0x90, 0x94, 0xf4,
	0x83, 0x03, 0x9d, 0xb6, 0x19, 0x7a, 0x72, 0x81, 0x10, 0x86, 0x34, 0x4d, 0x55, 0x9a, 0xe9, 0x4d,
	0x5d, 0xac, 0x17, 0xa3, 0x62, 0x69, 0xd5, 0xdd, 0x15, 0x89, 0x2f, 0x9d, 0x5e, 0x3b, 0x9d, 0xe9,
	0x9f, 0xd0, 0x43, 0xdb, 0xff, 0xb2, 0x97, 0x8e, 0xa4, 0x95, 0xbc, 0x16, 0xf2, 0xc7, 0xa1, 0x37,
	0xef, 0x6f, 0xdf, 0x7b, 0xbf, 0xf7, 0xa5, 0x7d, 0xcf, 0xb0, 0xf0, 0xd6, 0xf7, 0x30, 0x94, 0x34,
	0xf2, 0xf7, 0x22, 0xce, 0x24, 0x23, 0x8d, 0x02, 0xb0, 0x5d, 0x58, 0xfb, 0x0e, 0xf9, 0xb5, 0xdf,
	0x41, 0x07, 0xbb, 0xbe, 0x90, 0x9c, 0x4a, 0x9f, 0x85, 0x0e, 0x8a, 0x88, 0x85, 0x02, 0xc9, 0x26,
	0xcc, 0xa7, 0xa2, 0xbe, 0xec, 0xbb, 0xbe, 0x67, 0x1a, 0x2d, 0x63, 0xb7, 0xe1, 0x40, 0x0e, 0x9d,
	0x7a, 0x89, 0x80, 0xc8, 0xf4, 0xdd, 0x2b, 0xec, 0x9b, 0xb5, 0x4c, 0x40, 0x41, 0x67, 0xd8, 0xb7,
	0x7f, 0x37, 0xc0, 0xaa, 0x64, 0xf8, 0x39, 0x46, 0x21, 0xc9, 0x16, 0x34, 0x73, 0xfd, 0x90, 0x06,
	0xa8, 0x18, 0x72, 0x9b, 0xaf, 0x68, 0x80, 0xe4, 0x31, 0xdc, 0xcb, 0x45, 0xae, 0x31, 0xf4, 0x18,
	0x57, 0x2c, 0x77, 0x15, 0xfa, 0x26, 0x05, 0xc9, 0x36, 0xdc, 0x15, 0x71, 0x14, 0x31, 0x2e, 0x5d,
	0x0c, 0xa8, 0xdf, 0x33, 0xeb, 0xa9, 0x54, 0x53, 0x81, 0xc7, 0x09, 0x66, 0xef, 0x40, 0xb3, 0x1d,
	0xcb, 0xcb, 0x22, 0xbe, 0x65, 0xb8, 0x2d, 0xd9, 0x15, 0x86, 0x8a, 0x37, 0x3b, 0xd8, 0x9f, 0xc1,
	0x4a, 0x22, 0x75, 0x78, 0x49, 0x7b, 0x3d, 0x0c, 0xbb, 0x58, 0x88, 0x3f, 0x82, 0x46, 0x27, 0x07,
	0x95, 0xca, 0x00, 0xb0, 0xdf, 0xc0, 0x72, 0x49, 0x2d, 0x8b, 0x71, 0x62, 0x12, 0xd7, 0x01, 0x22,
	0xce, 0x7e, 0xc2, 0x8e, 0x4c, 0xee, 0xb3, 0xe8, 0x1a, 0x0a, 0x39, 0xf5, 0xec, 0xbf, 0x0c, 0x20,
	0xaf, 0x91, 0xbf, 0x65, 0x3c, 0xc8, 0x9c, 0x9f, 0xde, 0xec, 0x15, 0xf6, 0xdd, 0x4b, 0x1a, 0x7a,
	0x3d, 0xcc, 0xcd, 0x5e, 0x61, 0xff, 0x45, 0x0a, 0x94, 0x58, 0xeb, 0x25, 0x56, 0xf2, 0x09, 0x90,
	0x22, 0x34, 0x97, 0xab, 0x0c, 0x98, 0x33, 0xa9, 0xd8, 0x52, 0xa7, 0x9c, 0x1a, 0x3b, 0x86, 0x7b,
	0x89, 0x73, 0x67, 0xd8, 0xcf, 0xfd, 0xb3, 0x60, 0x2e, 0x16, 0xc8, 0xb5, 0xb2, 0x16, 0xe7, 0xe4,
	0x2e, 0xa2, 0x42, 0xbc, 0x63, 0x3c, 0x8f, 0xb7, 0x38, 0x93, 0x8f, 0x60, 0x29, 0x16, 0xb4, 0x8b,
	0xae, 0x87, 0xa2, 0xc3, 0xfd, 0x28, 0x69, 0x17, 0xe5, 0xde, 0x62, 0x7a, 0x71, 0x34, 0xc0, 0xed,
	0x3f, 0x0c, 0x58, 0x28, 0x78, 0x55, 0x95, 0xc6, 0x11, 0x97, 0x92, 0x56, 0xab, 0x6a, 0xe8, 0x88,
	0xfb, 0xd7, 0x54, 0x66, 0x0d, 0x9d, 0xf1, 0x82, 0x82, 0xce, 0xb0, 0x5f, 0xca, 0xea, 0x4c, 0x29,
	0xab, 0xf6, 0x9f, 0x06, 0xac, 0xbe, 0x64, 0x5d, 0x3f, 0x3c, 0xf7, 0x03, 0x14, 0x92, 0x06, 0x51,
	0xe1, 0xd7, 0x0b, 0xb8, 0xc3, 0x51, 0xc4, 0x3d, 0x29, 0x4c, 0xa3, 0x55, 0xdf, 0x9d, 0xdf, 0xdf,
	0xdb, 0x1b, 0x7c, 0x99, 0xd5, 0x3a, 0x7b, 0x4e, 0xa6, 0x70, 0x1c, 0x4a, 0xde, 0x77, 0x72, 0x75,
	0xeb, 0x00, 0x9a, 0xfa, 0x05, 0x59, 0x84, 0x7a, 0xe2, 0x6c, 0x16, 0x6c, 0xf2, 0x33, 0x69, 0xec,
	0x6b, 0xda, 0x8b, 0xb3, 0xb2, 0xd7, 0x9d, 0xec, 0x70, 0x50, 0x7b, 0x66, 0xd8, 0xcf, 0x60, 0xa5,
	0xcc, 0x35, 0xa2, 0x9f, 0xea, 0xc3, 0xa9, 0xb1, 0x3f, 0x87, 0xfb, 0xa7, 0xf9, 0xe9, 0x48, 0x8c,
	0x7e, 0x23, 0xca, 0x7a, 0xcb, 0x40, 0x86, 0xf4, 0x52, 0x3a, 0xfb, 0x00, 0x16, 0xdb, 0x9d, 0x0e,
	0x8b, 0x43, 0xd9, 0x96, 0x92, 0xfb, 0x17, 0xb1, 0xc4, 0x49, 0x71, 0x34, 0x54, 0x1c, 0xf6, 0xdf,
	0x06, 0xdc, 0x55, 0xca, 0x47, 0x28, 0xa9, 0xdf, 0x9b, 0xfc, 0x31, 0xe8, 0x4d, 0x51, 0x2b, 0x35,
	0xc5, 0x97, 0x00, 0x34, 0xf7, 0x41, 0x98, 0xf5, 0xb4, 0x36, 0x6b, 0x5a, 0x6d, 0xca, 0x7e, 0x3a,
	0x9a, 0x38, 0x31, 0xe1, 0x4e, 0x87, 0x23, 0x95, 0xe8, 0xa5, 0xcd, 0x50, 0x77, 0xf2, 0xa3, 0x7d,
	0x06, 0x2b, 0x43, 0x4e, 0x16, 0x19, 0xdb, 0x2f, 0x37, 0x82, 0x79, 0x93, 0x4c, 0xa9, 0xe4, 0x82,
	0xf6, 0x17, 0xb0, 0x5c, 0x32, 0x36, 0x65, 0xd5, 0xbe, 0x82, 0xcd, 0x13, 0x94, 0x5f, 0xd3, 0x90,
	0x76, 0x31, 0xc0, 0x50, 0xbe, 0x46, 0x1e, 0xf8, 0x42, 0xf8, 0x2c, 0x14, 0x53, 0xdb, 0xa0, 0xf0,
	0xa8, 0xca, 0xc0, 0xf4, 0x63, 0xa2, 0x05, 0xf3, 0xd1, 0x80, 0xd7, 0xac, 0xa5, 0x0c, 0x3a, 0x64,
	0x5f, 0xc0, 0xfa, 0x08, 0x1f, 0x15, 0x47, 0xbb, 0x9c, 0xb4, 0x0f, 0xb4, 0xa4, 0x8d, 0xf3, 0x6e,
	0x90, 0xc3, 0x16, 0x6c, 0xb4, 0x3d, 0xaf, 0x5a, 0x36, 0x7b, 0xc5, 0xe8, 0x18, 0x89, 0xe9, 0x72,
	0x45, 0x36, 0x00, 0x06, 0x71, 0xe5, 0x0f, 0xcc, 0x00, 0xb1, 0xb7, 0x61, 0xcb, 0xc1, 0x80, 0x5d,
	0xe3, 0x38, 0x3f, 0xbc, 0xf1, 0x42, 0xff, 0x93, 0x2b, 0xff, 0x18, 0x30, 0x7b, 0xc8, 0xd8, 0x95,
	0x8f, 0x84, 0xc0, 0x8c, 0xf6, 0x5e, 0xa6, 0xbf, 0xab, 0xbf, 0x3d, 0xb2, 0x0a, 0xb3, 0x1e, 0x0b,
	0xa8, 0x9f, 0xbf, 0xc9, 0xea, 0x94, 0xcc, 0x5f, 0x7c, 0x1f, 0xf9, 0x1c, 0x85, 0x8b, 0x11, 0xeb,
	0x5c, 0xaa, 0xaf, 0xa1, 0xa9, 0xc0, 0xe3, 0x04, 0x4b, 0x94, 0x05, 0x76, 0x62, 0x8e, 0xe6, 0xed,
	0x96, 0xb1, 0x3b, 0xe7, 0xa8, 0x13, 0x59, 0x83, 0xc6, 0xa5, 0x94, 0x91, 0xcb, 0xc2, 0x5e, 0xdf,
	0x9c, 0x4d, 0xaf, 0xe6, 0x12, 0xe0, 0x9b, 0xb0, 0xd7, 0xb7, 0x05, 0x98, 0x87, 0xe9, 0x27, 0xf5,
	0xbd, 0x40, 0xae, 0x3e, 0x82, 0x3c, 0x07, 0x09, 0x6b, 0x32, 0xd9, 0x5d, 0xea, 0x79, 0x1c, 0x85,
	0x50, 0x01, 0x34, 0x53, 0xb0, 0x9d, 0x61, 0x64, 0x1f, 0x56, 0x7c, 0x21, 0x62, 0x74, 0x25, 0x06,
	0x11, 0xe3, 0x94, 0xf7, 0xdd, 0x6c, 0xea, 0xd7, 0x52, 0xa6, 0xfb, 0xe9, 0xe5, 0x79, 0x7e, 0x77,
	0x9e, 0xee, 0x00, 0xef, 0xe1, 0x61, 0x05, 0xe9, 0xb4, 0xfd, 0x7e, 0x00, 0x0b, 0x55, 0x5c, 0xf3,
	0xfb, 0x4b, 0x5a, 0xd3, 0x66, 0xa9, 0x77, 0xee, 0xc9, 0x21, 0xe6, 0xfd, 0x7f, 0xe7, 0x60, 0x26,
	0x19, 0x69, 0x84, 0x82, 0x75, 0x82, 0x32, 0xf9, 0x99, 0xd8, 0xed, 0xa4, 0x7b, 0x53, 0xb1, 0x5c,
	0x90, 0x4d, 0xfd, 0xcd, 0xa8, 0x58, 0x3b, 0xac, 0xd6, 0x68, 0x01, 0x35, 0xb3, 0x6f, 0x91, 0x6f,
	0x61, 0x45, 0xdb, 0x2c, 0x06, 0x34, 0x64, 0x5d, 0x53, 0xbe, 0xb9, 0x7b, 0x58, 0x0f, 0x4a, 0xb6,
	0x35, 0x93, 0x0e, 0x3c, 0x38, 0x41, 0xf9, 0x0a, 0xdf, 0x0d, 0x5b, 0x4c, 0x46, 0xe7, 0xc3, 0x92,
	0xd6, 0x60, 0x59, 0xb0, 0xac, 0xaa, 0xab, 0xc2, 0x66, 0x17, 0x96, 0xb3, 0x62, 0xa8, 0x4d, 0x52,
	0xd5, 0x83, 0x3c, 0xd6, 0xb4, 0x46, 0x2f, 0x99, 0xd6, 0x93, 0x49, 0x62, 0x05, 0xd1, 0x8f, 0xb0,
	0x74, 0xa3, 0xea, 0x64, 0x5b, 0xaf, 0xd9, 0x88, 0x46, 0xb4, 0x76, 0xc6, 0x0b, 0x15, 0x0c, 0x2e,
	0xac, 0x9e, 0xa0, 0x7c, 0x49, 0x85, 0x1c, 0x9e, 0xc2, 0x82, 0xb4, 0xc6, 0x6c, 0x03, 0x19, 0xc7,
	0xd6, 0xc4, 0x7d, 0xc1, 0xbe, 0x45, 0x7e, 0x80, 0xa5, 0xa4, 0x6b, 0xf4, 0x59, 0x21, 0x86, 0x9b,
	0xa5, 0x62, 0x8c, 0x0c, 0x37, 0x4b, 0xd5, 0xd0, 0xb2, 0x6f, 0x91, 0xf3, 0xcc, 0x72, 0xaf, 0xa7,
	0x4d, 0xf3, 0xa1, 0x46, 0xb9, 0x39, 0xe5, 0xad, 0x8d, 0x51, 0xd7, 0x85, 0xd5, 0x5f, 0x0d, 0x78,
	0x32, 0x6a, 0x40, 0x3d, 0x67, 0x5c, 0xe7, 0xfa, 0x50, 0x33, 0x36, 0x61, 0xa6, 0x59, 0xbb, 0x13,
	0xa6, 0x83, 0xee, 0xc2, 0x2f, 0xb0, 0x33, 0xe2, 0xd5, 0x3f, 0x67, 0x3a, 0xff, 0x53, 0x3d, 0x49,
	0x63, 0xc7, 0x84, 0x35, 0x95, 0x68, 0xce, 0xff, 0x9b, 0x01, 0x4f, 0x47, 0x3f, 0xf7, 0xcf, 0x39,
	0x0b, 0x74, 0x2f, 0x3e, 0xd6, 0x4c, 0x4f, 0x1c, 0x12, 0xd6, 0xb4, 0xd2, 0xca, 0x97, 0x8b, 0xd9,
	0xf4, 0x2f, 0xe2, 0xa7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x40, 0x5e, 0x02, 0x35, 0x0e,
	0x00, 0x00,
}
